default: &default
  adapter: postgresql
  pool: 5
  encoding: UTF8
  timeout: 5000
  port: 5432

development:
  <<: *default
  username: user
  password: password
  database: self_destruction

test:
  <<: *default
  database: self_destruction_test

production:
  url: <%= ENV["DATABASE_URL"] %>
